accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from accounts.views import SignupView
from django.contrib import auth

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import ReceiptListView, ReceiptCreateView
from receipts.views import AccountListView, AccountCreateView
from receipts.views import ExpenseCategoryListView, ExpenseCategoryCreateView

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path("accounts/", AccountListView.as_view(), name="list_account"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.db.models import Model
from django.conf import settings

USERMODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USERMODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USERMODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USERMODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignupCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.views.generic import CreateView


class SignupView(CreateView):
    template_name = "registration/signup.html"
    success_url = reverse_lazy("login")
    form_class = UserCreationForm

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.purchaser = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("home", pk=plan.id)

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Receipt, Account, ExpenseCategory
from django.urls import reverse_lazy


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipt/list.html"
    # context_object_name = "receiptlist"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipt/create.html"
    success_url = reverse_lazy("create_receipt")
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "category",
        "account",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "account/list.html"
    fields = ["name", "number"]
    # context_object_name = "accountlist"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "account/create.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("list_account")

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "category/list.html"
    fields = ["name"]
    # context_object_name = "expenselist"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "category/create.html"
    fields = ["name"]
    success_url = reverse_lazy("list_categories")

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">My Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_account' %}">My Accounts</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated == False %}
                        <li>
                            <a href="{% url 'home' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/category/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/category/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Categories</h1>
            <h3>
                <li>
                    <a href="{% url 'create_category' %}">Create Category</a>
                </li>
            </h3>
            <table>
                <thead>
                    <th>Name</th>
                    <th>Numer of receipts</th>
                </thead>
                {% for list in expense_list %}
                    <tbody>
                        <td>{{ list.name }}</td>
                        <td>{{ list.receipts.all|length }}</td>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipt/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipt/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>My Receipts</h1>
        <li>
            <a href="{% url 'create_receipt' %}">Create Receipt</a>
        </li>
        <li>
            <a href="{% url 'create_account' %}">Create Account</a>
        </li>
        <li>
            <a href="{% url 'create_category' %}">Create Category</a>
        </li>
        <table>
            <thead>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Due Date</th>
                <th>Category</th>
                <th>Account</th>
            </thead>
            {% for list in receipt_list %}
                <tbody>
                    <td>{{ list.vendor }}</td>
                    <td>{{ list.total }}</td>
                    <td>{{ list.tax }}</td>
                    <td>{{ list.date|date:'m-d-Y' }}</td>
                    <td>{{ list.category }}</td>
                    <td>{{ list.account }}</td>
                </tbody>
            {% endfor %}
        </table>
    </main>
{% endblock content %}